### ISSUE TITLE
Preventing recursive serialization?

### ISSUE THREAD

**Issue by humblecoder** [ktekinay/Data-Serialization#2]
It seems that when an object is provided to a child for the purpose of "parental context", when the child object is serialized, the tool (understandably) enters an infinite loop.

Does XOJO provide a mechanism by which to track runtime object ids/hashes (via Introspection or otherwise) so that we can avoid this?

**Comment by ktekinay** [comment]
As far as I know, no, but these types of circular references should be avoided anyway. The best way to handle it is to create a computed property, Parent, on a shadow property of type WeakRef.

As far as serialization goes, you could modify the code so objects are stored in a Dictionary with an incrementing item id as the value. When a new object is to be serialized, it could check to see if it already exists in the Dictionary and, if so, could store a reference to it instead. Deserialization would have to look for those cases too, of course, using an opposite Dictionary (id as key, object as value). 

I hope that made sense.

**Comment by humblecoder** [comment]
Yeah, unfortunately, I don't control the codebase, the owner has built the application to *depend* on the existing references, and they're unwilling to make the adjustments needed.  😨 

Yup, makes total sense.  I was afraid of having to "manually" track them, which is why I was hoping for a unique object hash (or "in-memory" id) of some sort.  😢 

I'll see what I can come up with.  Thanks.
